### ISSUE TITLE
Some problem with using published map views in iframe

### ISSUE THREAD

**Issue by blackfolder** [oskariorg/oskari-docs#102]
Let's assume that we have a website http://localhost/szopatest/ that wants to use publish map view in iframe. 
![website](https://user-images.githubusercontent.com/32539683/54687794-b509da00-4b1c-11e9-9bcc-65c0d561052d.png)
<html>
<body>
szopatest
<iframe src="http://liiteridev.ymparisto.fi:8080/oskari-map/?lang=fi&uuid=9ad6bb92-ace9-40e0-90d0-eb6f83e6c901" allow="geolocation" style="border: none; width: 100%; height: 100%;"></iframe>
</body>
</html>

Then, when the content of the iframe is loaded, there's a request send and the referer (http://localhost/szopatest/) for published domain is checked. And that works completely fine. 
![form](https://user-images.githubusercontent.com/32539683/54687896-f7331b80-4b1c-11e9-9592-4b4a0bd8c8c7.png)
![MapController](https://user-images.githubusercontent.com/32539683/54687903-fbf7cf80-4b1c-11e9-84d2-5d3469fd2979.png)
![firstRequest](https://user-images.githubusercontent.com/32539683/54687915-00bc8380-4b1d-11e9-96c9-e1e8cb8807e9.png)

Then, there's another request with action_route=GetAppSetup (see: secondRequest.png). This time the browser sets the referer according the iframe source. In the GetAppSetupHandler, there's also referer check for published map performed. 
![GetAppSetupHandler](https://user-images.githubusercontent.com/32539683/54687951-0c0faf00-4b1d-11e9-9ea9-ce5964f02471.png)

And this time, the access to the published map view will be denied and map in the iframe won't be loaded. This is related to the new browsers' referer policy (https://stackoverflow.com/questions/8468335/what-is-the-http-referer-if-the-link-is-clicked-in-an-iframe/32139089).

To fix that problem I'd suggest modify a bit referer check for published map views in the GetAppSetupHandler to support old and new way of setting referer by browser.
![solution](https://user-images.githubusercontent.com/32539683/54687995-1f227f00-4b1d-11e9-91ae-a0631ec80f33.png)

**Comment by ZakarFin** [comment]
As a workaround you could add the domain of the Oskari instance to oskari-ext.properties:

# Allow published maps to be loaded from these domains
view.published.usage.unrestrictedDomains = localhost, [your domain]

https://github.com/oskariorg/sample-configs/blob/master/jetty-9/oskari-server/resources/oskari-ext.properties#L74

This will also fix an issue for clicking the preview link in users "My data" for an embedded map. But sure the value of oskari.domain property could be automatically added to the whitelist. Since you've already modified the code can you submit a pull request for this https://github.com/oskariorg/oskari-server? You can just add the oskari.domain value to the UNRESTRICTED_USAGE_DOMAINS for this method https://github.com/oskariorg/oskari-server/blob/master/service-map/src/main/java/fi/nls/oskari/map/view/util/ViewHelper.java#L56

**Comment by blackfolder** [comment]
Thanks! I'll submit a pull request for that according to your guidance.

**Comment by ZakarFin** [comment]
I added a pr so the workaround for this doesn't need to be done manually oskariorg/oskari-server#569 so closing this
