### ISSUE TITLE
Print map of the specified area

### ISSUE THREAD

**Issue by ernoma** [oskariorg/oskari-docs#161]
Currently the map area that is printed is based on the zoom level and on the selected page size and orientation. It would be very useful that the user would be able to draw the area that should be fitted in the printed map.

For example, at the city of Tampere, we have a need to print a master plan map in A3 size (landscape in this case) from Oskari but with the available zoom levels either the map is remarkably too small on the A3 print size or if zoomed one step in, then the master plan area wont fit to the A3 print size anymore.

**Comment by jampukka** [comment]
Is this still an issue?

**Comment by ernoma** [comment]
It is still an issue, because currently we create the archived and lawfully binding master plan PDF maps via the Oskari print tool. See an example, https://www.tampere.fi/tiedostot/y/2kT6VlvMB/Kartat_1-4_maarayksineen_uusi.pdf

**Comment by jampukka** [comment]
It seems that atleast with WFS and WMS layers this isn't too much of an issue, just change the `resolution` in the the request.

WFS example with `resolution=4`: `https://demo-kartta.paikkatietoikkuna.fi/action?action_route=GetPrint&coord=391151_6668918&mapLayers=952+30+default&srs=EPSG:3067&resolution=4&pageSize=A4&format=application/pdf`

Same layer with `resolution=6.25`: `https://demo-kartta.paikkatietoikkuna.fi/action?action_route=GetPrint&coord=391151_6668918&mapLayers=952+30+default&srs=EPSG:3067&resolution=6.25&pageSize=A4&format=application/pdf`

WMS example `resolution=0.25`: `https://demo-kartta.paikkatietoikkuna.fi/action?action_route=GetPrint&coord=391879_6670801&mapLayers=1691+100+cp:CP.CadastralBoundary.Default&srs=EPSG:3067&resolution=0.25&pageSize=A4&format=application/pdf`

Same layer with `resolution=0.37`: `https://demo-kartta.paikkatietoikkuna.fi/action?action_route=GetPrint&coord=391879_6670801&mapLayers=1691+100+cp:CP.CadastralBoundary.Default&srs=EPSG:3067&resolution=0.37&pageSize=A4&format=application/pdf`

With WMTS layers you run into an exception [here](https://github.com/oskariorg/oskari-server/blob/master/service-print/src/main/java/org/oskari/print/loader/CommandLoadImageWMTS.java#L183) because we can't find TileMatrix (zoom level) with matching resolution. Changing the logic to pick the TileMatrix with the closest resolution would be trivial, but probably wouldn't be enough. One would probably have to rewrite the logic that fetches and combines the tiles into an image in `CommandLoadWMTS` and add some scaling there to get it working properly. That shouldn't be too difficult.

**Comment by ernoma** [comment]
Thank you! That works. For example:
https://kartat.tampere.fi/oskari/action?action_route=GetPrint&zoomLevel=7&coord=328001.2608441943_6820245.965370067&mapLayers=2777+100+,2891+100+&srs=EPSG:3067&resolution=16.8&scaleText=&pageSize=A3_Landscape&format=image/png&pageTitle=

Also, I did not previously notice that the print tool shows the URL at the web browser location field after choosing the print options and pressing the print button.
