### ISSUE TITLE
Setting oskari.locales=id_ID,en_US,fi_FI,sv_SE,es_ES breaks Oskari from loading

### ISSUE THREAD

**Issue by senoadiw** [oskariorg/oskari-docs#194]
Oskari version: 1.55.2

The default locale is set to **id_ID** but Oskari tries to load dist/1.2.1/geoportal/oskari_lang_**in**.js which does not exist. However setting the lang parameter to lang=es loads oskari_lang_es.js properly. @ZakarFin suggested to use in_ID for now.

Screenshot of error in js console:
![image](https://user-images.githubusercontent.com/1198399/80958127-b4bac400-8e2e-11ea-9509-e02c5668a98d.png)

**Comment by ZakarFin** [comment]
The Indonesian locale is tricky with the backwards compatibility decisions made on Java as a programming language. The actual problem here is java.util.Locale changes `id` to `in`. Here's some additional info for this with tests on the server-side code: https://github.com/oskariorg/oskari-server/pull/577

The suggested workaround is to use `in_ID` as locale for Indonesia in oskari-ext.properties and use `in` on oskari-frontend locales.

**Comment by senoadiw** [comment]
I just noticed after changing the locale from id_ID to in_ID, the top language in the edit theme box changed from id to English. But I can still edit and save the value.

![image](https://user-images.githubusercontent.com/1198399/81034394-33604180-8ec1-11ea-80a3-6fa5daf45d23.png)
