### ISSUE TITLE
Support environment variables as config

### ISSUE THREAD

**Issue by jampukka** [oskariorg/oskari-docs#262]
I would like to add support for allowing environment variables to override/take precedence over `oskari.properties` or `oskari-ext.properties`. Implementation should be rather straightforward as most if not all code accessing properties uses `PropertyUtil`.

The plan is to change `PropertyUtil.getProperty("my.key")` to first check if an environment variable `MY_KEY` (uppercased and dots replaced by underscores) has a set value and if so, use that value instead.

Should we require prefixing the environment variables (e.g. `OSKARI_MY_KEY` <=> `my.key`) not to conflict with other programs?

**Comment by ZakarFin** [comment]
This would a nice improvement. I would add the prefixing for env variables since names in oskari-ext.properties can assume they are only for the specific app while env variables are "global" scoped. So while doing an env variable for `OSKARI_OSKARI_DOMAIN` to override `oskari.domain` property feels funky, it's still better to prevent something like `DB_USER` (to override `db.user`) being declared for Oskari but used accidentally by some other application as database password from shared env variables :)

**Comment by ZakarFin** [comment]
Thanks! Included in 2.6.0.
