### ISSUE TITLE
GetGeoLocatorSearchResult and Reverse Geocoding

### ISSUE THREAD

**Issue by Dranu** [oskariorg/oskari-docs#52]
Hello,

I'm not sure if this is an issue or not but I cannot for the life of me figure out how to get the reverse geocoding part to work i.e. searching with lat and lon instead of a search term. 

Your documentation (http://www.oskari.org/documentation/backend/actionroutes/getGeoLocatorSearchResult) says that the action can be used without "term" but if it is empty, the error "{"error":"Search string was null"}" comes up even with lat and lon present. 
Cannot get it to work with https://kartta.paikkatietoikkuna.fi/ either. I can get the normal searching to work with good results with Paikkatietoikkuna on Oskari on localhost but would've liked to use the reverse geocoding as well.

**Comment by ZakarFin** [comment]
Hi,

The reverse geocoding isn't triggered by the same search UI, but with this icon:

![reverse-geocode](https://user-images.githubusercontent.com/2210335/30273640-8ff2dac0-9702-11e7-9771-2276fb53d046.png)

If there are multiple results (from multiple search channels or many from one)  the results are shown with markers and a popup. If there's only one result the "infobox" component (popup that's attached to the map location) is used to show the result. The tool itself is created by adding this bundle to the appsetup: https://github.com/oskariorg/oskari-frontend/tree/master/bundles/framework/findbycoordinates

The GeoLocator referenced on that page is a service that's not publicly accessible (which is weird since we reference it in the docs...). Anyways, for a search channel to provide reverse geocoding it should:

1) implement getCapabilities() which returns a value allowing reverse search: https://github.com/oskariorg/oskari-server/blob/master/service-search-opendata/src/main/java/fi/nls/oskari/search/What3WordsSearchChannel.java#L98-L100

2) Implement the method to search based on coordinates: https://github.com/oskariorg/oskari-server/blob/master/service-search-opendata/src/main/java/fi/nls/oskari/search/What3WordsSearchChannel.java#L151

Here's a link to the action handler that's used to trigger calls on the search channels for reverse geocoding: https://github.com/oskariorg/oskari-server/blob/master/control-base/src/main/java/fi/nls/oskari/control/data/GetReverseGeocodingResultHandler.java
