### ISSUE TITLE
Scale ratio in print tool / map window

### ISSUE THREAD

**Issue by SannaJokela** [oskariorg/oskari-docs#57]
Is it possible to have scale ratio info also in print tool and at the same time also in the map window? Like 1:250 000 (This was suggested in Oskari Joint Development Forum)

**Comment by ZakarFin** [comment]
It's possible to include yes. Someone just needs to implement it.

**Comment by jampukka** [comment]
What is the use case here? Taking a ruler and measuring stuff from the screen will not yield correct results (it might in some extreme, but change your resolution and it will not anymore). For PDF printouts it does make some sense, since PDF is fixed at 72DPI, but only when actually printed out (not when viewed on screen). Also the zoom levels rarely correspond to any exact scale denominator, so you will end up with arbitrary scale ratios of for example 1:1521.541. Is that useful information?

Also, scale calculations will work super poorly in small scales in projections with heavy distortion in high up north (for example in EPSG:4326 used in demo.oskari.org).

**Comment by SannaJokela** [comment]
True. This was my thoughts also. In my opinion the scalebar should be enough. With GIS software it is possible to have scales and play around with them, e.g. you need to print your map layout with scale of 1:25 000 > this would be probably the use case.

**Comment by ZakarFin** [comment]
So basically this would mean more work than it's probably worth to be useful for anyone. Close as "won't fix"?

**Comment by ZakarFin** [comment]
There's something related to this included in 1.48.0 in oskariorg/oskari-frontend#437 and oskariorg/oskari-server#235. Not sure if this is what you were after, but you should check it out.

**Comment by ZakarFin** [comment]
No-one seems too exited to develop this so closing the issue.
