### ISSUE TITLE
Layer external info url and description

### ISSUE THREAD

**Issue by kuosman** [oskariorg/oskari-docs#96]
# Info

New description or/and link button on layers. I think at both buttons is the best solution.
New buttons are displayed per layer in layer-selection2, layer-selector2 and hierarchical layerlist if layer has saved data for this columns in database.

Description button opens a popup and show saved localized description for current map layer. Popup is closed by pressing the Close button
External link button opens saved url to new window. Link is also localized.

Two approaches:
* make these features available for all (described here) or
* make these features for app specific (app specific oskari-frontend and oskari-server-extension). These functions can be done here, because app uses hierarchical-layerlist and there can be add buttons from another bundle (like admin hierarchical layerlist makes)

# How to

## Database

New two columns in oskari_maplayer -table:
* `info_url`: varchar (2000)
* `description`: text

New columns are created by flyway.

## Server

All core changes:

* update sql clauses
* update maplayer domain class
* maplayer save/update updates for support new functionalities

## Core

* maplayer dom changes to support info_url and description
* also JSON parsing changes

### Bundle `admin-layerselector`

* add new text inputs (localized info url and localized description)
* add support to save function to support new inputs
* add info_url and description support for edit layer
* add support to update map layer

### Bundle `layer-selection2`

* new layer tool `Info from external datasource` (new icon)
* new layer tool `Description` (new icon)

### Bundle `layer-selector2`

* new layer tool `Info from external datasource` (new icon)
* new layer tool `Description` (new icon)

### Bundle `hierarchical-layerlist`

* new layer tool `Info from external datasource` (new icon)
* new layer tool `Description` (new icon)

**Comment by ZakarFin** [comment]
What happens if both info-URL AND description are defined? Could description be saved as the current "subtitle"? Changed in the frontend so it would be opened in a new window if the text is over ~100 characters or so? I think the info_url could be just saved to layer attributes or options instead of a new field. Also the description could be saved on some other table than oskari_maplayer.

Another way to do this could be adding a new "links" element for layers. Links could be "external links" (== info url), metadata links (== current metadata id), links to content on some light CMS implementation included in Oskari (== description).

**Comment by ZakarFin** [comment]
I think the links could be saved in the oskari_maplayer "attributes" field in the database instead of a new field or table as a part of the JSON it currently has. Something like:

    {
        "links": [{
            "url": "https://asdfasfd",
            "locale": { "fi": "linkki", "en": "link"}
        }],
       .... other attributes ...
    }

This could be further developed to include the metadataId instead of having it in a separate field etc.

As for the description I think it should be a new table. Something that would work with the GetArticlesByTag action route that we have now. So the table would have fields for id, "tags" that are used by GetArticlesByTag, perhaps a language field, title field and the actual content. This content could also be mapped to layers with the above links definition by adding something like:

    {
            "type": "article",
            "tags": "something",
            "locale": { "fi": "lisätietoja", "en": "more info"}
    }

Managing the content would be a new admin bundle. Linking content to layers would need some request or service to hook up new admin-functionality for layers in the layer admin so the functionality isn't required to be part of the Oskari instance. Changes to the layerselector etc can have the handling built-in as it's not that much of a code to generate the links in the UI.

**Comment by ZakarFin** [comment]
PRs could be something like:
1) Add support for basic links in layers (for end user and admins)
2) Add support for admin-form to have injected parts from other bundles
3) Add CMS content support (new admin bundle + GetArticleByTags improvement)
4) Add support for linking CMS content to layers with a new admin bundle hooking in to the existing form with functionality developed in step 2?

**Comment by kuosman** [comment]
not being implemented at this time

**Comment by ZakarFin** [comment]
Ok, closing this one for now. It can be reopened if there's more interest in this
